spring:
  profiles:
    active: dev
    include: secret
---

spring:
  config:
    activate:
      on-profile: dev

cors:
  allow-origin: "http://localhost:5173"

springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.project.zero_wait_back.entity